### ISSUE TITLE
《Operating Systems: Three Easy Pieces》中文版

### ISSUE THREAD

**Issue by zozospider** [liuyubobobo/ai-learning-roadmap#2]
老师好，《Operating Systems: Three Easy Pieces》有中文版，由异步图书出品。个人认为是一本浅显易懂的操作系统入门好教材。
中文版京东购买点击[这里](https://item.jd.com/12535621.html)。

**Comment by liuyubobobo** [comment]
谢谢你！相关内容已经更新，并且添加了你的名字，引向你的 github 主页：）
